// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_clhwang.Models;

namespace Mission06_clhwang.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    partial class MovieApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission06_clhwang.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Romantic Comedy",
                            Director = "Mark Rosman",
                            Edited = false,
                            Notes = "This is my go-to movie.",
                            Rating = "PG",
                            Title = "A Cinderella Story",
                            Year = 2004
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Action/Adventure",
                            Director = "Joe Russo",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Avengers: Endgame",
                            Year = 2019
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Romantic Comedy",
                            Director = "Gil Junger",
                            Edited = false,
                            Notes = "This is a classic.",
                            Rating = "PG-13",
                            Title = "10 Things I Hate About You",
                            Year = 1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
